version: '3.9'

networks:
  techmove-network:
    name: techmove-network

services:
  postgres-server:
    container_name: postgres-server
    image: postgres:${POSTGRESQL_VERSION}
    hostname: ${POSTGRESQL_HOST}
    ports:
      - ${POSTGRESQL_EXTERNAL_PORT}:${POSTGRESQL_PORT}
    volumes:
      - ${POSTGRESQL_PATH}:/var/lib/postgresql/data
    networks:
      - techmove-network
    environment:
      POSTGRESQL_DB: ${POSTGRESQL_DB}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      TZ: "America/Fortaleza"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRESQL_DB} -U $${POSTGRESQL_USER}"]
      interval: 10s
      timeout: 30s
      retries: 10