version: '3.9'

networks:
  techmove-network:
    name: techmove-network

services:
  postgres-server:
    container_name: postgres-server
    image: postgres:${POSTGRES_VERSION}
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    networks:
      - techmove-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "America/Fortaleza"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 10